# Generated by Django 4.2.2 on 2023-07-29 19:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=12)),
                ('gst_no', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 1, 0, 50, 807420)),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=10)),
                ('po_number', models.CharField(blank=True, max_length=10)),
                ('add', models.CharField(default='0', max_length=100)),
                ('due', models.CharField(default='0', max_length=100)),
                ('remove', models.CharField(max_length=100)),
                ('purpose', models.TextField(default='For Business purpose')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 7, 30, 1, 0, 50, 818358))),
                ('status', models.CharField(choices=[('Add', 'Add'), ('Due', 'Due'), ('Widthrawl', 'Withdrawl')], default='Due', max_length=100)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=10)),
                ('po_number', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 7, 30, 1, 0, 50, 809964))),
                ('invoice_status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], default='Due', max_length=100)),
                ('invoice_id', models.UUIDField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('po_number', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True)),
                ('quantity', models.BigIntegerField(default=0)),
                ('subtotal', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('paid_amt', models.CharField(max_length=100)),
                ('due_amt', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 7, 30, 1, 0, 50, 812162))),
                ('invoice_id', models.UUIDField(unique=True)),
                ('invoice_status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], default='Due', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.customer')),
                ('invoice_items', models.ManyToManyField(to='tools.invoice_item')),
                ('products', models.ManyToManyField(to='tools.product')),
            ],
        ),
    ]
