# Generated by Django 4.2.2 on 2023-07-29 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_contact_customer_alter_product_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 2, 8, 24, 988744)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_amt',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amt',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 2, 8, 24, 986517)),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='add',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 2, 8, 24, 995885)),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='due',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='remove',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 2, 8, 24, 983391)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
