# Generated by Django 4.2.2 on 2023-08-02 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_phone_number_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, upload_to='static/pdfs/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 1, 42, 4, 996444)),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 1, 42, 4, 994273)),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 1, 42, 5, 4278)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 1, 42, 4, 991693)),
        ),
    ]
